AWSTemplateFormatVersion: 2010-09-09          # Template version
Description: A sample template                # Template description
Resources:                                    # Define AWS resources
  MyEC2Instance:                              # Resource name
    Type: 'AWS::EC2::Instance'                # Resource type (EC2 instance)
    Properties:                               # Resource properties
      ImageId: ami-079b5e5b3971bd10d          # AMI ID
      InstanceType: t2.micro                  # Instance type
      KeyName: windows                        # Key pair name
      SubnetId: subnet-0fb711bb0db5adf11      # Subnet ID
      BlockDeviceMappings:                    # Define block device mappings (EBS volume)
        - DeviceName: /dev/sdm                # Device name
          Ebs:
            VolumeType: io1                   # EBS volume type
            Iops: 200                         # Provisioned IOPS
            DeleteOnTermination: true         # Delete volume on instance termination
            VolumeSize: 8                     # Volume size (in GB)
  MyEIP:                                      # Elastic IP resource
    Type: 'AWS::EC2::EIP'                     # Resource type (Elastic IP)
    Properties:                               # Resource properties
      InstanceId: !Ref MyEC2Instance          # Associate EIP with EC2 instance
